[workspace]
resolver = "2"
members = ["typedflake", "typedflake-core", "typedflake-macros", "examples/axum-sqlx"]

[workspace.package]
version = "0.2.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
authors = ["pokedotdev <hi@poke.dev>"]
repository = "https://github.com/pokedotdev/typedflake"
homepage = "https://github.com/pokedotdev/typedflake"

[workspace.dependencies]
typedflake = { path = "typedflake" }
typedflake-core = { path = "typedflake-core" }
typedflake-macros = { path = "typedflake-macros" }
dashmap = "6.1"
derive_more = { version = "2.0.1", features = ["error", "from", "display"] }
serde = { version = "1.0" }
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full", "parsing"] }
criterion = { version = "0.7", features = ["html_reports"] }
serde_json = "1.0"
